# Generated by Django 3.2.7 on 2021-09-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_manufacturer', models.CharField(max_length=100)),
            ],
        ),
    ]
